[package]
name = "act"
version = "18.0.2"
edition = "2024"

[dependencies]
rust-ini = "0.21"
clap = { version = "4.5.*", features = ["env"] }

[profile.release]
strip = true # does not minimize binary size in nix build
lto = true
codegen-units = 1
